apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  #this defines which pods are part of this service
  #service becomes a network endpoint for either other services or external users to connect. Checking with Meshery
  selector:
    app: app-service
  ports:
    - name: http
      port: 80
      targetPort: 8082
      NodePort: 30080
  type: NodePort
